"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TremoloMode = exports.ReverbType = exports.PreAmpType = exports.PowerAmpType = exports.PhaserMode = exports.PedalType = exports.ModulationType = exports.FlangerMode = exports.factory = exports.DistortionMode = exports.DelayType = exports.ChorusMode = exports.CabinetType = exports.AutoWahMode = exports.CodeApi = void 0;
const marshallcode_1 = __importDefault(require("./marshallcode"));
exports.CodeApi = marshallcode_1.default;
const Patch_1 = require("./Patch");
Object.defineProperty(exports, "AutoWahMode", { enumerable: true, get: function () { return Patch_1.AutoWahMode; } });
Object.defineProperty(exports, "CabinetType", { enumerable: true, get: function () { return Patch_1.CabinetType; } });
Object.defineProperty(exports, "ChorusMode", { enumerable: true, get: function () { return Patch_1.ChorusMode; } });
Object.defineProperty(exports, "DelayType", { enumerable: true, get: function () { return Patch_1.DelayType; } });
Object.defineProperty(exports, "DistortionMode", { enumerable: true, get: function () { return Patch_1.DistortionMode; } });
Object.defineProperty(exports, "factory", { enumerable: true, get: function () { return Patch_1.factory; } });
Object.defineProperty(exports, "FlangerMode", { enumerable: true, get: function () { return Patch_1.FlangerMode; } });
Object.defineProperty(exports, "ModulationType", { enumerable: true, get: function () { return Patch_1.ModulationType; } });
Object.defineProperty(exports, "PedalType", { enumerable: true, get: function () { return Patch_1.PedalType; } });
Object.defineProperty(exports, "PhaserMode", { enumerable: true, get: function () { return Patch_1.PhaserMode; } });
Object.defineProperty(exports, "PowerAmpType", { enumerable: true, get: function () { return Patch_1.PowerAmpType; } });
Object.defineProperty(exports, "PreAmpType", { enumerable: true, get: function () { return Patch_1.PreAmpType; } });
Object.defineProperty(exports, "ReverbType", { enumerable: true, get: function () { return Patch_1.ReverbType; } });
Object.defineProperty(exports, "TremoloMode", { enumerable: true, get: function () { return Patch_1.TremoloMode; } });
